.github/workflows/matrix.yaml
provision-cluster/create.js
provision-cluster/gke.js
provision-cluster/gke.test.js
provision-cluster/lib/kubeception.js
provision-cluster/lib/utils.js
provision-cluster/lib/utils.test.js

Each commit should be simple to review in isolation:
- Switch default timeout to one hour.
- Move uid, fibonacciDelaySequence, and sleep into lib/utils.js
- Add missing await.
- Add fibonacciRetry as a convenience method.
- Wire up fibonacciRetry for kubeception.
- Use fibonacciRetry for GKE also.

Make kubeception use fibonacci retry.

---

github-runner-provisioner/README.md
github-runner-provisioner/config.go
github-runner-provisioner/requesthandler.go

Uses the `go-github` `ValidatePayload` function to validate webhook calls with the webhook secret. 
Testing: Tested in another repository. I couldn't get local testing working - even with directly copied headers and payloads. 
Deployment plan: 
Update the `github-runner-provisioner-secrets` with the webhook token value & apply
Merge PR
Monitor rollout in argo
Run webhook to confirm it works

Use auth webtoken

---

github-runner-provisioner/macm1.go

When a Mac M1 was being ran, we didn't specify an availability zone which sometimes caused this error:
```
Error creating Mac M1 runner for job run_tests (macOS-arm64, Kubeception, 1.19) [https://github.com/telepresenceio/telepresence/actions/runs/3390344647/jobs/5634405291]: operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: 951170cb-293f-437f-ae33-8029f8bdeace, api error UnsupportedHostConfiguration: Your requested instance type (mac2.metal) is not supported in your requested Availability Zone (us-east-1c). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1d.
```
This PR updates the instance placement to use zone us-east-1a

Specify an availability zone when creating Mac M1 instances

---

github-runner-provisioner/github-runner-provisioner.yaml
github-runner-provisioner/main.go

Exposed the health check on `/github-runner-provisioner/healthz` so we can monitor the provisioner using an uptime check.
Ran app locally and checked that the old URLs are still reachable, and the health check returns a 200 code

Expose the health check endpoint to be able to do an uptime check

---

README.md
docs/ACTION_RUNNERS.md
docs/CLUSTERS.md
docs/GITHUB_ACTIONS.md

This PR updates documentation as follows:
- Document how to configure the self-hosted runner Webhook on a repository
- Clean-up existing docs
- Split docs into smaller files

Document GitHub webhook setup and doc clean-up

---

.github/workflows/deploy_tests.yaml
github-runner-provisioner/github-runner-provisioner.yaml

It's taking close to 2 minutes for the action runner provisioner to be build so the pod gets killed because the health check fails.
Increased health and ready check and set pod resources/limits which may help with a faster build.
None I can think of
Build will test this changes
None
Just merge the PR

Increase health check delay since it takes longer to build the GitHub runner provisioner

---

github-runner-provisioner/github-runner-provisioner.yaml

Container is taking over 2 minutes to start and this is causing failures due to the health check failing.
I made the following changes to correct the issue:
1. Added a pod disruption budget so there is always one pod alive even when there is an eviction.
2. Added a startup probe that waits up to 3 minutes for the pod to be ready
3. Updated health and ready probes to fail after the first error so they are more sensitive to service failures.
4. Set deployment replicas to 2
If probes don't behave as expected it will cause downtime.
- Tested in a Kluster that app starts correctly and health/ready checks work
- Tested that disruption budged will prevent all replicas from being evicted at the same time.
Merge PR and check that pod starts correctly

Add a pod disruption budget and update probes to handle pod evictions better

---

provision-cluster/action.yaml
provision-cluster/lib/common_test.js
provision-cluster/lib/gke.test.js
provision-cluster/lib/kubeception.js
provision-cluster/lib/kubeception.test.js
provision-cluster/lib/mock.js
provision-cluster/lib/registry.js

Add support for the kubeceptionProfile token. The first commit is mostly a minor refactor to allow
testing of the kubeception SPI with a mock http client. Each commit can be reviewed independently
for easier consumption:
- Make kubeception implementation mockable and turn gke test into a shared lifecycle test.
- Add a kubeceptionProfile parameter along with a test.
Small: if this is broken it would break any github workflows that use this action, however since
they are pinned, this would only happen when users voluntarily upgrade.
My testing strategy is to use a mock http client that can then assert that the correct parameters
are being passed to kubeception. This permits fast local unit tests and is robust so long as the
kubeception API remains stable/backwards compatible.
This is …

Add kubeceptionProfile input.

---

.github/workflows/smoke.yaml
provision-cluster/action.yaml

The `provision-cluster` action was not working when referenced using the syntax `datawire/infra-actions/provision-cluster@VERSION` since the action could not find all the files required to run.
To fix this, the first thing action does is to check out the source of the version being used.
None. Repos used pinned versions.
Tested by referencing the action from the Telepresence Pro [repo](https://github.com/datawire/telepresence-pro/actions/runs/3833478103).
N/A
N/A

Fix cluster-provisioning action

---

.github/workflows/deploy_tests.yaml
github-runner-provisioner/github-runner-provisioner.yaml

Added ServiceMonitor that's required so Prometheus scrapes metrics
None
Tested manually by adding a service monitor and checking that the metrics are scraped by Prometheus.
Merge PR and check that metrics are being collected

Add service monitor to GitHub action runner provisioner

---

github-runner-provisioner/kustomization.yaml

This will tel ArgoCD to exclude configmaps generated by kustomize from the syns status.
This will make the application appear as in-sync when a new version of the app is deployed.
None I can think of
I'll test it once chane is deployed.
Make sure that new versions of the configmaps do not make the app show as out of sync.

Tell ArgoCD to ignore configmaps that are generated by kustomiz from the diff.

---

github-runner-provisioner/go.mod
github-runner-provisioner/go.sum
github-runner-provisioner/internal/monitoring/prometheus.go
github-runner-provisioner/requesthandler.go

This change adds a counter that will track different errors that can happen when the action runner provisioner finds an error while processing a request from GitHub.
In addition, I improved logging for errors during provisioning
None.
Note: There is a different corrective action for creating a checklist for this app.
Manual tests to verify that the counter increases when there is an error.
[Add an alert for when the GitHub runner provisioner can’t create runners.](https://www.notion.so/datawire/Add-an-alert-for-when-the-GitHub-runner-provisioner-can-t-create-runners-90a2312f5aee4a52a38554bb25d7e416)
Merge PR

Expose a Prometheus metric for GitHub runner provisioning errors

---

Makefile
github-runner-provisioner/github.go
github-runner-provisioner/internal/monitoring/prometheus.go
github-runner-provisioner/requesthandler.go

The function that checks if a GitHub runner is available was swallowing errors, which made it harder to troubleshoot issues.
Also, when a runner was already available, the provisioner ignored this and created a new one.
I also fixed the following issues:
- Instructions for generating an SHA used in tests, which made testing this harder.
- Added missing labels in a Prometheus counter
It could break provisioning of new runners
Run the app locally and checked that a runner can be provisioned

Improve check for available runners

---

github-runner-provisioner/github-runner-provisioner.yaml
github-runner-provisioner/internal/monitoring/prometheus.go
github-runner-provisioner/requesthandler.go

If the provisioner fails to create a runner, an alert will be sent to #health-monitors.
The following errors are tracked:
1. Provisioner can't list existing runners in GitHub, which will prevent creation of new ones.
2. An error happened while provisioning a new runner in AWS.
None
I'll test that the alert triggers after it's deployed.
Cause an error by blocking the `d6eautomaton` user from being able to query existing runners, and make sure that alert is sent to slack.
- [Add an alert for when the GitHub runner provisioner can’t create runners](https://www.notion.so/datawire/Add-an-alert-for-when-the-GitHub-runner-provisioner-can-t-create-runners-90a2312f5aee4a52a38554bb25d7e416).
Merge PR

Send an alert when the provisioner has issues creating a GitHub runner

---

github-runner-provisioner/github-runner-provisioner.yaml

Update the runner provisioner alert to be easier to read by including additional information like the runner label and the repository affected.
Existing alert could break.

Update provisioner alert to be more descriptive

---

github-runner-provisioner/main.go
github-runner-provisioner/requesthandler.go

GRP is logging non-error results as errors, making logs less useful and potentially clouding future monitoring efforts. 
Minimal, no direct impacts at the moment. 
Minimal testing required, compiles and logs as expected. 
N/A
Fire and forget 👍

Reduce log level for non-errors

---

codemagic.yaml
github-runner-provisioner/internal/aws/aws_runners/macm1.go
github-runner-provisioner/internal/aws/aws_runners/ubuntuarm64.go

The GitHub Runner version is deprecated, causing runners to fail to pick up new jobs and just circle on an error. By bumping the version runners will be able to pick up jobs again.
Things are already broken, this can't really make them worse. 
Allocated an M1 runner to the Infra Actions repo and ran a simple "hello world" job. 
Merge and restart the waiting jobs to allocate new runners.

Bump GitHub Runner version to 308

---

.github/actions/provision-cluster/README.md
.github/workflows/matrix.yaml
.github/workflows/smoke.yaml
docs/GITHUB_ACTIONS.md

GKE 1.23 is no longer supported. Updated the base Kubernetes version to 1.27. Ideally this would be the latest 1.29 version, but Kubeception does not yet support this (although that will be changing this week), so we'll start with the minimum 1.27 version consistently first.

Updating base Kubernetes versions to 1.27

---

.github/workflows/github-runner-provisioner.yaml

The Docker login does not work, as it's (presumably) still using a password and not a proper PAT.
Added a new PAT to Docker Hub (and correspondingly to GitHub secrets).
Upgraded the standard GitHub Actions version for this workflow.
(I'll update the rest of the workflows after this...)

Use DockerHub token instead of password

---

.github/workflows/github-runner-provisioner.yaml
.github/workflows/matrix.yaml

Skip (main) CI workflows when only `markdown` files change. We want to be able to update/maintain documentation without triggering obtrusive workflows (particularly those with either costly tests, or production impact).

Skip CI on markdown only changes

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

It's always debatable, but I prefer to keep minimal, relevant VSCode settings/extensions in the repo directly.
This is just to keep consistency on some basic best practices.
In this case, it's basically a bomb waiting to go off, because none of the Javascript files are formatted per standards.
I'll probably just format them all (automatically) in the future, but I've been avoiding it so far.

Add default VSCode settings/extensions

---

.github/actions/provision-cluster/lib/kubeception.js
.github/actions/provision-cluster/lib/utils.js
.github/actions/provision-cluster/lib/utils.test.js

Improves the Kubeception retry handling slightly. This is intended to be a minimal refactor, without changing too much of the existing code. Normally, I would improve this retry logic, instead of adding a non-error `Retry` error, but I think this works under the circumstances, and is fairly clear. Similarly, some of the logging indicates an "error" when it may not technically be an error situation, but I don't want to overanalyze the existing code.
This is heavily weighted on the side of retrying on anything unexpected, but the consumers of this logic are going to want/prefer reliability, not speed.
This also expands to be more flexible in the future. i.e. both 200/201 should be consider success, and 202 is a better use-case for the Kubeception kubeconfig handling, rather than 425 (which …

Refactor Kubeception retry handling

---

.github/actions/provision-cluster/lib/registry.js
.github/workflows/matrix.yaml

Create the cluster client when necessary, rather than instantiate global distribution clients.
Minimally reworks the `matrix` tests to ensure both sets of credentials are not passed for all distributions.
Closes #66

Cluster clients are created as needed

---

.github/actions/provision-cluster/lib/kubeception.js
.github/actions/provision-cluster/lib/kubeception.test.js

Migrates to the new kluster kubeconfig endpoint. Put/Get kluster commands will no longer have the option to return the kubeconfig directly in future iterations. Applying minimal refactoring for now, leaving most of the existing logic in place.

Update to use new kluster kubeconfig endpoint

---

.github/workflows/matrix.yaml

Updates `matix.yaml` to always run when pushing to the `main` branch.

Run Matrix CI on push to main

---

.github/actions/gke-kubeconfig/action.yaml
.github/workflows/expire.yaml
.github/workflows/matrix.yaml
.github/workflows/smoke.yaml
docs/GITHUB_ACTIONS.md

* Upgrades `kubectl` auth handling to avoid the [removed, built-in GCP auth handling](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke). For now, this primarily means using the internal `useAuthProvider: "false"` configuration.
* Refactors all tests (and documentation) to remove the combined used of GKE and Kubeception, and instead splits everything into discrete tests for each provider. The combined use was not appropriate due to the nature of the provisioning, and it was additionally hiding defects.
* Removes "Telepresence" naming from the primary matrix test, as it does not (nor should it) install Telepresence, or have anything to do with Telepresence.
* Upgrades the versions of the Google Cloud auth actions.
* Removes the deprecated/removed …

Update kubectl auth in CI

---

.github/actions/provision-cluster/README.md
.github/workflows/smoke.yaml
docs/GITHUB_ACTIONS.md

Upgrades to latest provision-cluster version (v0.3.0)

Upgrade provision-cluster to v0.3.0

---

.github/actions/provision-cluster/lib/kubeception.js
.github/actions/provision-cluster/lib/slack.js

The use of Node was upgraded from 16 to 20, per the rapidly approaching [deprecation of Node 16 in GitHub Actions](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20).
Noting that GitHub Actions does not support Node 18.
The use of Node 20 (by virtue of [Node 19](https://nodejs.org/en/blog/release/v19.0.0)) has changed `keepAlive` to be true by default.
> Starting with this release, Node.js sets keepAlive to true by default. This means that any outgoing HTTP(s) connection will automatically use HTTP 1.1 Keep-Alive.
This has had an impact on a great number of GitHub Actions. Reference [setup-ruby](https://github.com/ruby/setup-ruby/issues/543#issuecomment-1793608370) for one such issue.
Additionally, the `@actions/http-client` (which we are using) …

Set keepAlive to false

---

.github/actions/provision-cluster/README.md
.github/workflows/smoke.yaml
docs/GITHUB_ACTIONS.md

Updates the smoke test and documentation to reference the latest version `datawire/infra-actions/provision-cluster@v0.3.1`.

Upgrade provision-cluster to v0.3.1

---

.github/actions/provision-cluster/README.md
.github/workflows/matrix.yaml
.github/workflows/smoke.yaml
docs/GITHUB_ACTIONS.md

Update our baseline Kubernetes version to v1.29. GKE no longer supports v1.27, so these tests/docs are officially outdated and unsupported. We don't support v1.30 and v1.31 in Kubeception (yet, and I'll probably deal with that tomorrow), and I'll update this handling accordingly after we do.
N/A
N/A
N/A

Update from Kubernetes 1.27 to 1.29

---

.github/actions/provision-cluster/action.yaml
.github/actions/provision-cluster/lib/kubeception.js
.github/actions/provision-cluster/lib/kubeception.test.js
provision-cluster/action.yaml

* Switches from Skunkworks to Production.
* Updates the Kubeception client to the latest OpenAPI schema.
NOTES:
* Nothing currently uses a (different) Kubeception profile other than the disabled `saas_app` system tests which have not functioned for a long time for a variety of reasons, so there's no reason to support setting the archetype yet. We'll consider adding this in the distant future if/when necessary.
* The Skunkworks tokens that support the various repos have already been migrated to production, so this should work transparently.
* None of the existing use will use these changes unless we upgrade the `provision-cluster` version in the various repos.
Limited, particularly due to the fact that it will require releasing a new `provision-cluster` version and then updating the …

Update Kubeception client to use production
