datawire/infra-actions

.github/workflows/matrix.yaml
Better comments and docs for the matrix v0.
=> Better comments/documentation for the matrix.yaml file

.github/workflows/expire.yaml, .github/workflows/matrix.yaml, provision-cluster/action.yaml, provision-cluster/create.js, provision-cluster/delete.js, provision-cluster/gke.js, provision-cluster/gke.test.js, provision-cluster/mock.js, provision-cluster/registry.js
- More complete/cleaner mock.
- Wire up GKE provisioner.
- Shrink the matrix and add kubectl.
=> GKE Provisioner Wiring

github-runner-provisioner/README.md, github-runner-provisioner/github-runner-provisioner.yaml, github-runner-provisioner/go.mod, github-runner-provisioner/kustomization.yaml, github-runner-provisioner/main.go
Add github runner provisioner skeleton.
=> Add github runner provisioner skeleton.

github-runner-provisioner/github-runner-provisioner.yaml
Fix ingress to use mapping instead of load balancer.
=> Fix ingress to use mapping instead of load balancer.

README.md
Sample job using an Ubuntu ARM64 runner and details about how they work
=> Document how to use Ubuntu ARM64 runners

.github/workflows/deploy_tests.yaml, github-runner-provisioner/github-runner-provisioner.yaml, github-runner-provisioner/kustomization.yaml
This PR adds files that are required to run the provisioner, and also a build workflow that will prevent this issue in the future.
Provisioner pod would not start if this doesn't work as expected. However, the old pod will not be destroyed until the new one is running.
Made sure the build passes
None
Just merge
=> Add missing files to kustomization.yaml

.github/workflows/smoke.yaml, docs/GITHUB_ACTIONS.md, provision-cluster/action.yaml, provision-cluster/create.js
Updated provision-cluster action to return additional information for GKE clusters
Nothing expected. Tests pass with GKE and Kubeception clusters.
Updated smoke tests
None
N/A
=> Return clustrer information

.github/workflows/expire.yaml, provision-cluster/action.yaml
Remove bad parameter in call to provision-cluster when expiring clusters.
See a sample failure [here](https://github.com/datawire/infra-actions/actions/runs/4000359102)
None, It's already broken.
Run workflow
N/A
=> Fix cluster expiration workflow

.github/actions/provision-cluster/lib/gke.js, .github/workflows/matrix.yaml
We cannot use the gkeConfig parameter because it's not parse before using it.
List any potential negative consequences of a bug in this change, and how do we know if something is broken.
A few sentences describing your tests. For example:
1. What changes are not tested and why.
2. What changes are riskier, and how are they tested.
=> Add json parsing for gkeConfig

provision-cluster/action.yaml
Right now, the caller workflow get it's workspace erase by the provision-cluster actions. Adding a path to prevent that.
List any potential negative consequences of a bug in this change, and how do we know if something is broken.
A few sentences describing your tests. For example:
1. What changes are not tested and why.
2. What changes are riskier, and how are they tested.
=> Prevent workspace conflict with caller workflow

provision-cluster/action.yaml
I forgot to fix the paths as well. I did it in my test branch but forgot to add it in my PR.
List any potential negative consequences of a bug in this change, and how do we know if something is broken.
A few sentences describing your tests. For example:
1. What changes are not tested and why.
2. What changes are riskier, and how are they tested.
=> Fix new paths

.github/workflows/github-runner-provisioner.yaml
Workflow must run on push to main
=> Run workflow on push to main

.github/workflows/github-runner-provisioner.yaml
=> Fix build on main

codemagic.yaml, github-runner-provisioner/internal/aws/aws_runners/macm1.go
Fix runner arch for M1 runners
N/A
N/A
N/A
Fire & forget
=> Actually use arm runner :zany:

github-runner-provisioner/github.go, github-runner-provisioner/internal/aws/aws.go, github-runner-provisioner/internal/aws/aws_runners/macm1.go, github-runner-provisioner/internal/aws/aws_runners/shared.go, github-runner-provisioner/internal/aws/aws_runners/ubuntuarm64.go, github-runner-provisioner/internal/aws/ec2.go, github-runner-provisioner/internal/aws/iface.go, github-runner-provisioner/internal/aws/runner.go, github-runner-provisioner/internal/aws/runner_test.go, github-runner-provisioner/internal/codemagic/runner.go, github-runner-provisioner/internal/monitoring/prometheus.go, github-runner-provisioner/internal/monitoring/runner.go, github-runner-provisioner/requesthandler.go, github-runner-provisioner/runner.go
=> Formatting

.github/workflows/expire.yaml, .github/workflows/matrix.yaml, .github/workflows/tests.yaml, docs/ACTION_RUNNERS.md, provision-cluster/action.yaml
Updates to the latest GitHub Actions.
=> Update to latest GitHub Actions

.github/workflows/github-runner-provisioner.yaml
Also ignore markdown-only changes on push to main...
=> Ignore markdown-only changes on push

.github/actions/provision-cluster/README.md
Expand documented example usages of the `provision-cluster` action.
=> Expand documented examples

.github/actions/provision-cluster/create.js, .github/actions/provision-cluster/delete.js, .github/actions/provision-cluster/lib/gke.js, .github/actions/provision-cluster/lib/gke.test.js, .github/actions/provision-cluster/lib/kubeception.test.js, .github/actions/provision-cluster/lib/mock.js, .github/actions/provision-cluster/lib/utils.js, .github/workflows/tests.yaml
* Fixes lint errors
* Adds lint check to CI
=> Fix lint errors (and add linting to CI)

.github/workflows/smoke.yaml
Updates the smoke test to the latest tag (v0.2.7).
=> Update smoke test version to latest

.github/actions/provision-cluster/create.js, .github/actions/provision-cluster/delete.js, .github/actions/provision-cluster/lib/common_test.js, .github/actions/provision-cluster/lib/gke.js, .github/actions/provision-cluster/lib/gke.test.js, .github/actions/provision-cluster/lib/kubeception.js, .github/actions/provision-cluster/lib/kubeception.test.js, .github/actions/provision-cluster/lib/mock.js, .github/actions/provision-cluster/lib/slack.js, .github/actions/provision-cluster/lib/utils.js, .github/actions/provision-cluster/lib/utils.test.js
Autoformats all Javascript files per standards, prior to more substantial changes.
[.vscode/settings.json](https://github.com/datawire/infra-actions/blob/main/.vscode/settings.json) in this repo has the settings defined for VSCode, but these are the conventional settings that should be used in any dev environment.
=> Auto-formatting Javascript files

.github/actions/provision-cluster/README.md, .github/workflows/smoke.yaml, docs/GITHUB_ACTIONS.md
Updates the smoke test (and readme files) to the latest `provision-cluster` version v0.2.9.
=> Update to latest release version (v0.2.9)

.github/actions/provision-cluster/action.yaml, docs/GITHUB_ACTIONS.md, provision-cluster/action.yaml
Remove references to unimplemented cluster providers.
=> Remove unimplemented cluster providers

.github/workflows/smoke.yaml
Adds a workflow dispatch option to the smoke test CI to enable on-the-fly testing.
=> Add workflow dispatch to smoke test

.github/workflows/github-runner-provisioner.yaml, .github/workflows/matrix.yaml, .github/workflows/smoke.yaml
Updates GitHub Actions to latest. This specifically targets a few new version updates that are necessary due to the deprecation of Node 16 and the transition to Node 20, but it's good practice to keep these updated regularly anyway.
N/A
Existing, broad test suites.
N/A
N/A
=> Update github actions

.github/actions/provision-cluster/README.md, .github/workflows/matrix.yaml, .github/workflows/smoke.yaml, docs/GITHUB_ACTIONS.md
Update all of our test workflows and documents to use the latest release version (and the latest Kubernetes version).
N/A
Existing test suites.
N/A
N/A
=> Update tests/docs to latest release
